### ISSUE TITLE
KeyError: 'video'

### ISSUE THREAD

**Issue by ZachPlzSleepEarly** [vladan-stojnic/Detection-of-Flying-Honeybees-in-UAV-Videos#3]
Dear Vladan Stojnić👋, 

When I tried to stabilize the video, I gave the absolute path to the [video file](https://zenodo.org/record/4400651#.YqVj6blBxf0) and the absolute path to the output folder, a KeyError: 'video' was raised. Could you help me solve the problem? 🙏

```console
(bee4exp) root@container-85b211b6ac-a1f45001:~/autodl-tmp/paper2# python stabilization.py -i /root/autodl-tmp/paper2/Videos/bgs/background_seq1.mp4 -o /root/autodl-tmp/paper2/Video_output
100
Traceback (most recent call last):
  File "stabilization.py", line 38, in <module>
    rate = metadata['video']['@r_frame_rate']
KeyError: 'video'
(bee4exp) root@container-85b211b6ac-a1f45001:~/autodl-tmp/paper2# 
```

**Comment by ZachPlzSleepEarly** [comment]
Here are the downloaded video files supported by the paper
</br>
<img width="314" alt="Screen Shot 2022-06-12 at 12 01 05 PM" src="https://user-images.githubusercontent.com/72327157/173213823-a0505cfc-7002-460a-99c8-fd0bb1847df2.png">

**Comment by vladan-stojnic** [comment]
Hi Andrew,

Sorry for the late reply. I am unable to reproduce your error. I have just created an environment using provided .yml file and after that I was able to run the stabilization script without errors. KeyError: "video" usually shows up if path to the video is not correct. However since in your output there is a correct number of frames shown (100), path should be correct. Maybe downloaded files are somehow corrupted and you need to redownload them. Also you can try running the script on some other videos as it should be able to run on anything. If files are not corrupted then I have no idea what is causing the error. In stabilisation script you could overcome the problem by changing line 
`rate = metadata['video']['@r_frame_rate']` into `rate = str(fps) + "/1"`, however this is only a fix to this script and there might be similar problems in other ones.
